name: Atualizar lista de projetos

on:
  schedule:
    - cron: '0 6 * * *'  # Executa todo dia 맙 03:00 da manh칚 (hor치rio Brasil)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar reposit칩rio
      uses: actions/checkout@v3

    - name: Gerar lista de reposit칩rios automaticamente
      uses: marketplacerepo/github-profile-readme-generator@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ithalo-teodosio
        CUSTOM_PROJECTS_SECTION_TITLE: 游 Meus Projetos
        MAX_REPOS: 10
        SORT_BY: updated
        IGNORE_FORKS: true

    - name: Commit e push caso tenha altera칞칫es
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "chore: atualiza칞칚o autom치tica da lista de projetos" || exit 0
        git push
